### ISSUE TITLE
Incomplete plugin?

### ISSUE THREAD

**Issue by countach74** [getsentry/sentry-teamwork#1]
It may be that I'm trying to use something that's not complete yet, but I can't seem to get this working correctly. Once the URL and API key are configured, there doesn't seem to be a way to configure which project to send stuff to, etc. I'm using Sentry 7.6.2.

If this is simply under development still, is there a rough time frame until it will be complete? Also, I may be able to lend a hand if that is at all desired.

**Comment by dcramer** [comment]
This plugin may not work in Sentry 7.6. The project is selected when you go to create a new task, and is populated via JS.
